#!/usr/bin/env bash
# ZPOD image scaffold. Safe by default: no clone, no build, no flashing.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${ROOT}/config/zpod.env"
PI_GEN_DIR="${ROOT}/build/pi-gen"
GEN_CONFIG="${ROOT}/build/pi-gen-config"

confirm=0
do_build=0
board=""

usage() {
  cat <<EOF
ZPOD image scaffold — does not flash an SD card.

Usage:
  ./build.sh
      Print this help and exit 0. Does not clone or build.

  ./build.sh --confirm --board pi0|pi0w
      Clone RPi-Distro/pi-gen (branch master, 32-bit) into build/pi-gen
      if it is not already there, and write build/pi-gen-config.
      Does not start the image build.

  ./build.sh --confirm --board pi0|pi0w --build
      After the clone, run pi-gen. This takes hours, needs root, a Debian-like
      host, and tens of gigabytes. It still does not write any SD card.
      Refusing to flash is intentional: copy the image yourself, and only
      onto a card you have confirmed is disposable.

Boards:
  pi0    Raspberry Pi Zero     (no onboard radio)
  pi0w   Raspberry Pi Zero W   (onboard Wi-Fi/Bluetooth)

pi-gen is not deprecated (checked 2026-10). It remains the official Raspberry
Pi OS image builder. rpi-image-gen is an alternative for custom images, not
the default here. Pi Zero / Zero W must stay on pi-gen master (armhf), not
the arm64 branch.

TFT driver, button pinout, DAC, and battery-board wiring are unknown.
Do not invent them. See config/zpod.yaml.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)
      usage
      exit 0
      ;;
    --confirm)
      confirm=1
      shift
      ;;
    --build)
      do_build=1
      shift
      ;;
    --board)
      board="${2:-}"
      if [[ -z "$board" ]]; then
        echo "error: --board needs pi0 or pi0w" >&2
        exit 2
      fi
      shift 2
      ;;
    --board=*)
      board="${1#--board=}"
      shift
      ;;
    *)
      echo "error: unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ "$confirm" -ne 1 ]]; then
  usage
  exit 0
fi

case "$board" in
  pi0|pi0w) ;;
  *)
    echo "error: --confirm requires --board pi0 or --board pi0w" >&2
    exit 2
    ;;
esac

if [[ ! -f "$ENV_FILE" ]]; then
  echo "error: missing $ENV_FILE" >&2
  exit 1
fi

# shellcheck disable=SC1090
set -a
source "$ENV_FILE"
set +a

repo="${PI_GEN_REPO:?PI_GEN_REPO missing}"
branch="${PI_GEN_BRANCH:?PI_GEN_BRANCH missing}"

if [[ "$branch" == "arm64" ]]; then
  echo "error: refusing arm64 branch; Pi Zero and Zero W are armhf" >&2
  exit 1
fi

echo "board:    $board"
echo "image:    ${IMG_NAME:-zpod}"
echo "pi-gen:   $repo ($branch)"
echo "checkout: $PI_GEN_DIR"

if [[ ! -d "$PI_GEN_DIR/.git" ]]; then
  echo "cloning pi-gen (not vendored)..."
  git clone --branch "$branch" --depth 1 "$repo" "$PI_GEN_DIR"
else
  echo "pi-gen checkout already present; not re-cloning"
fi

wireless_note="This board has no onboard radio. Do not require Wi-Fi to boot."
if [[ "$board" == "pi0w" ]]; then
  wireless_note="Zero W has onboard Wi-Fi/Bluetooth. WPA_COUNTRY is left unset (${WPA_COUNTRY:-empty})."
fi

cat > "$GEN_CONFIG" <<EOF
# Generated by build.sh. Do not commit (gitignored). Re-run --confirm to refresh.
# Board: ${board}
# ${wireless_note}
IMG_NAME='${IMG_NAME:-zpod}'
RELEASE='${RELEASE:-trixie}'
DEPLOY_COMPRESSION='${DEPLOY_COMPRESSION:-xz}'
TARGET_HOSTNAME='${TARGET_HOSTNAME:-zpod}'
LOCALE_DEFAULT='${LOCALE_DEFAULT:-en_US.UTF-8}'
KEYBOARD_KEYMAP='${KEYBOARD_KEYMAP:-us}'
TIMEZONE_DEFAULT='${TIMEZONE_DEFAULT:-America/Los_Angeles}'
FIRST_USER_NAME='pi'
# Password intentionally unset so the first-boot wizard locks the account
# until a person sets one. Do not bake a default password into this repo.
STAGE_LIST='stage0 stage1 stage2'
EOF

if [[ "$board" == "pi0w" && -n "${WPA_COUNTRY:-}" ]]; then
  echo "WPA_COUNTRY='${WPA_COUNTRY}'" >> "$GEN_CONFIG"
fi

cat >> "$GEN_CONFIG" <<EOF

# Hardware placeholders from config/zpod.env. Empty means unknown.
# TFT_DRIVER='${TFT_DRIVER:-}'
# TFT_DTOVERLAY='${TFT_DTOVERLAY:-}'
# DAC_CHIP='${DAC_CHIP:-}'
# DAC_BUS='${DAC_BUS:-}'
EOF

echo "wrote $GEN_CONFIG"
echo "TFT/DAC/buttons/battery pinout: unknown — image will not drive the panel yet."

if [[ "$do_build" -ne 1 ]]; then
  echo
  echo "stopped before the image build."
  echo "when the disposable card is confirmed and pinout is known, re-run:"
  echo "  ./build.sh --confirm --board $board --build"
  exit 0
fi

echo
echo "WARNING: starting pi-gen. This does not flash a card, but it will use"
echo "sudo, loop devices, and a lot of disk for several hours."
echo "dependencies (install yourself; this script does not apt-install):"
echo "  coreutils quilt parted qemu-user-binfmt debootstrap zerofree zip \\"
echo "  dosfstools e2fsprogs libarchive-tools libcap2-bin rsync xz-utils \\"
echo "  file git curl bc gpg pigz xxd arch-test bmap-tools kmod"
echo "  On a non-Debian host, qemu-user-static may be required instead of"
echo "  qemu-user-binfmt. Docker (build-docker.sh) is the other supported path."

if [[ ! -x "$PI_GEN_DIR/build.sh" ]]; then
  echo "error: $PI_GEN_DIR/build.sh missing; clone failed?" >&2
  exit 1
fi

# pi-gen sources ./config from its own tree unless -c is passed. Pass -c.
# Preserve the caller's cwd semantics by running inside the clone.
exec sudo -- "$PI_GEN_DIR/build.sh" -c "$GEN_CONFIG"
